/* eslint-disable max-len */
export default [
  {
    image: 'https://ads-decor.ua/cache/800x800/theme/ee_catalogprops_15/as-119-ruchka-bokova-shyrokyj-paz.jpg',
    label: 'БП 119',
    value: 'sp119',
    colors: ['silver-as', 'light-bronze-ao', 'dark-bronze-ab', 'rose-gold-wg', 'gold-ag', 'qraphite-gr', 'black-matte-bm', 'wenge-gloss-bw', 'oak-gloss-bo', 'nickel-brush-an', 'black-brush-bb', 'light-bronze-brush-bc', 'graphite-brush-gb', 'white-wh'],
    connectingProfiles: ['cp03', 'cp31', 'cp32'],
    mechanismes: ['mechanism-bushing-asymmetric', 'mechanism-silicon-asymmetric', 'mechanism-strengthened-asymmetric'],
    X1: 26,
  },
  {
    image: 'https://ads-decor.ua/cache/800x800/theme/ee_catalogprops_41/as-06-ruchka-bokova-shyrokyj-paz.jpg',
    label: 'БП 06',
    value: 'sp06',
    colors: ['silver-as', 'light-bronze-ao', 'dark-bronze-ab', 'rose-gold-wg', 'gold-ag', 'qraphite-gr', 'black-matte-bm', 'wenge-gloss-bw', 'oak-gloss-bo', 'nickel-brush-an', 'graphite-brush-gb', 'white-wh'],
    connectingProfiles: ['cp03', 'cp31', 'cp32'],
    mechanismes: ['mechanism-bushing-symmetric', 'mechanism-silicon-symmetric', 'mechanism-strengthened-symmetric'],
    X1: 32,
  },
  {
    image: 'https://ads-decor.ua/cache/800x800/theme/ee_catalogprops_23/as-07-ruchka-bokova-shyrokyj-paz.jpg',
    label: 'БП 07',
    value: 'sp07',
    colors: ['silver-as', 'light-bronze-ao', 'dark-bronze-ab', 'rose-gold-wg', 'gold-ag', 'qraphite-gr', 'black-matte-bm', 'wenge-gloss-bw', 'oak-gloss-bo', 'nickel-brush-an', 'black-brush-bb', 'light-bronze-brush-bc', 'graphite-brush-gb', 'white-wh'],
    connectingProfiles: ['cp03', 'cp31', 'cp32'],
    mechanismes: ['mechanism-bushing-asymmetric', 'mechanism-silicon-asymmetric', 'mechanism-strengthened-asymmetric'],
    X1: 41,
  },
  {
    image: 'https://ads-decor.ua/cache/800x800/theme/ee_catalogprops_48/as-117-ruchka-bokova-shyrokyj-paz.jpg',
    label: 'БП 117',
    value: 'sp117',
    colors: ['silver-as', 'light-bronze-ao', 'dark-bronze-ab', 'rose-gold-wg', 'gold-ag', 'qraphite-gr', 'black-matte-bm', 'wenge-gloss-bw', 'oak-gloss-bo', 'nickel-brush-an', 'black-brush-bb', 'light-bronze-brush-bc', 'graphite-brush-gb', 'white-wh', 'chrome-pl'],
    connectingProfiles: ['cp03', 'cp31', 'cp32'],
    mechanismes: ['mechanism-bushing-symmetric', 'mechanism-silicon-symmetric', 'mechanism-strengthened-symmetric'],
    X1: 50,
  },
  {
    image: 'https://ads-decor.ua/cache/800x800/theme/ee_catalogprops_32/as-120-ruchka-bokova-shyrokyj-paz.jpg',
    label: 'БП 120',
    value: 'sp120',
    colors: ['silver-as', 'light-bronze-ao', 'dark-bronze-ab', 'rose-gold-wg', 'gold-ag', 'qraphite-gr', 'black-matte-bm', 'wenge-gloss-bw', 'oak-gloss-bo', 'nickel-brush-an', 'black-brush-bb', 'light-bronze-brush-bc', 'graphite-brush-gb', 'acura-brush-ac', 'tawny-fy', 'white-wh', 'chrome-pl'],
    connectingProfiles: ['cp03', 'cp31', 'cp32'],
    mechanismes: ['mechanism-bushing-symmetric', 'mechanism-silicon-symmetric', 'mechanism-strengthened-symmetric'],
    X1: 41,
  },
  {
    image: '/src/client/assets/images/no-image.jpg',
    label: 'БП 207',
    value: 'sp207',
    colors: ['silver-as', 'light-bronze-ao', 'dark-bronze-ab', 'rose-gold-wg', 'qraphite-gr', 'black-matte-bm', 'wenge-gloss-bw', 'nickel-brush-an', 'black-brush-bb', 'light-bronze-brush-bc', 'graphite-brush-gb', 'acura-brush-ac', 'tawny-fy', 'white-wh', 'chrome-pl'],
    connectingProfiles: ['cp231'],
    mechanismes: ['mechanism-silicon-for-207-asymmetric'],
    X1: 13,
  },
  {
    image: 'https://ads-decor.ua/cache/800x800/theme/ee_catalogprops_153/1930.jpg',
    label: 'БП Slim',
    value: 'spSlim',
    colors: ['silver-as', 'dark-bronze-ab', 'qraphite-gr', 'black-matte-bm', 'nickel-brush-an', 'black-brush-bb', 'graphite-brush-gb', 'acura-brush-ac', 'tawny-fy', 'white-wh', 'chrome-pl'],
    connectingProfiles: ['cpSlim01', 'cpSlimDecor'],
    mechanismes: ['mechanism-bushing-symmetric', 'mechanism-silicon-symmetric', 'mechanism-strengthened-symmetric'],
    X1: 8,
  },
  {
    image: 'https://ads-decor.ua/cache/800x800/theme/ee_catalogprops_163/83.jpg',
    label: 'БП 219',
    value: 'sp219',
    colors: ['silver-as', 'light-bronze-ao', 'dark-bronze-ab', 'rose-gold-wg', 'gold-ag', 'wenge-gloss-bw'],
    connectingProfiles: ['cp03', 'cp31', 'cp32'],
    mechanismes: ['mechanism-silicon-mini'],
    X1: 30,
  },
  {
    image: 'https://ads-decor.ua/cache/800x800/theme/ee_catalogprops_55/as-119-l-ruchka-bokova-lajt.jpg',
    label: 'БП 119L',
    value: 'sp119L',
    colors: [],
    connectingProfiles: ['cp03L'],
    mechanismes: ['mechanism-bushing-asymmetric', 'mechanism-silicon-asymmetric', 'mechanism-strengthened-asymmetric'],
    X1: 25,
  },
  {
    image: 'https://ads-decor.ua/cache/800x800/theme/ee_catalogprops_224/as.jpg',
    label: 'БП 119v.p.',
    value: 'sp119VP',
    colors: [],
    connectingProfiles: ['cp03L'],
    mechanismes: ['mechanism-bushing-asymmetric', 'mechanism-silicon-asymmetric', 'mechanism-strengthened-asymmetric'],
    X1: 26,
  },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'БП 419',
  //   colors: ['silver-as', 'black-brush-bb', 'chrome-pl'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'БП 900',
  //   colors: ['silver-as', 'black-matte-bm', 'black-brush-bb', 'acura-brush-ac', 'tawny-fy', 'white-wh', 'wenge-matte-wm'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'P 31',
  //   colors: ['silver-as'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'P 32',
  //   colors: ['silver-as', 'light-bronze-ao', 'black-brush-bb', 'chrome-pl'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'P 33',
  //   colors: ['silver-as', 'light-bronze-ao', 'dark-bronze-ab', 'gold-ag', 'wenge-gloss-bw', 'nickel-brush-an', 'black-brush-bb', 'light-bronze-brush-bc', 'white-wh'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'P 34',
  //   colors: ['silver-as', 'nickel-brush-an', 'black-brush-bb', 'light-bronze-brush-bc', 'white-wh', 'chrome-pl'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'P 36',
  //   colors: ['silver-as', 'qraphite-gr', 'black-matte-bm', 'black-brush-bb', 'acura-brush-ac', 'tawny-fy', 'white-wh', 'chrome-pl'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'P 37',
  //   colors: ['silver-as', 'black-matte-bm', 'black-brush-bb', 'acura-brush-ac', 'tawny-fy'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'P 38',
  //   colors: ['silver-as', 'black-matte-bm', 'black-brush-bb', 'acura-brush-ac', 'tawny-fy'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'Air B1',
  //   colors: ['light-bronze-ao', 'black-matte-bm'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'Air B2',
  //   colors: ['light-bronze-ao', 'black-matte-bm'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'T18',
  //   colors: ['silver-as'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'T20',
  //   colors: ['silver-as'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'C16',
  //   colors: ['silver-as'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'C18',
  //   colors: ['silver-as', 'black-brush-bb', 'white-wh', 'chrome-pl'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'TC19',
  //   colors: ['silver-as'],
  // },
  // {
  //   image: '/src/client/assets/images/no-image.jpg',
  //   label: 'C20',
  //   colors: ['silver-as'],
  // },
];
